Added git branch validation pattern
Due to auto release note, branch pattern must be followed.

diff --git a/.github/workflows/pr-auto-semver.yml b/.github/workflows/pr-auto-semver.yml
--- a/.github/workflows/pr-auto-semver.yml
+++ b/.github/workflows/pr-auto-semver.yml
@@ -34,7 +34,6 @@ jobs:
       PR_TITLE: ${{ github.event.pull_request.title }}
       PR_BODY: ${{ github.event.pull_request.body }}
     steps:
-
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
@@ -140,3 +139,26 @@ jobs:
 
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+  branch-name:
+    name: Validate branch name pattern
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check branch name pattern
+        # For the pattern see also ../release-drafter-labeler-config.yml
+        env:
+          BRANCH: ${{ github.head_ref }}
+        run: |
+          if [[ "${BRANCH}" == "develop" ]]; then
+            echo "Branch name is 'develop', skipping pattern check"
+            exit 0
+          fi
+          if [[ "${BRANCH}" == "main" ]]; then
+            echo "Branch name is 'main', skipping pattern check"
+            exit 0
+          fi
+          expected_pattern="^(feature|feat|bugfix|bug|hotfix|hot|data|norn|skip-rn)[/_-].+$"
+          if [[ ! "${BRANCH}" =~ ${expected_pattern} ]]; then
+            echo "Invalid branch name: ${BRANCH}, expected pattern: ${expected_pattern}"
+            exit 1
+          fi
